import { Test } from "@nestjs/testing";
import { Queries } from "../../neo4j/neo4j.queries";
import { Neo4jService } from "../../neo4j/neo4j.service";
import { ProgramController } from "./program.controller";
import { v4 as generateUuid, version as uuidVersion, validate as uuidValidate } from 'uuid';
import * as request from 'supertest';

export function validUuidV4(uuid: string) {
  return uuidValidate(uuid) && uuidVersion(uuid) === 4;
}

describe('ProgramController', () => {
  let programController;
  let neo4jService;
  let app;

  beforeEach(async () => {
    const neo4jServiceMockProvider = {
      provide: Neo4jService,
      useFactory: () => ({execute: jest.fn()})
    }

    const moduleRef = await Test.createTestingModule({
      controllers: [ProgramController],
      providers: [neo4jServiceMockProvider],
    })
    .compile();

    app = await moduleRef.createNestApplication().init();

    programController = moduleRef.get<ProgramController>(ProgramController);
    neo4jService = moduleRef.get<Neo4jService>(Neo4jService);
  })

  describe('creating program node', () => {
    test('rejects with missing name', async () => {
      await request(app.getHttpServer())
        .post('/program')
        .send({})
        .expect(400)
        .then(response => {
          expect(response.body.message).toEqual(['code should not be empty', 'code must be a string', 'name should not be empty', 'name must be a string']);
        });
    });

    test('rejects with empty name', async () => {
      await request(app.getHttpServer())
        .post('/program')
        .send({name: '', code: ''})
        .expect(400)
        .then(response => {
          expect(response.body.message).toEqual(['code should not be empty', 'name should not be empty']);
        });
    });

    test('rejects with name not a string', async () => {
      await request(app.getHttpServer())
        .post('/program')
        .send({name: 5, code: 5})
        .expect(400)
        .then(response => {
          expect(response.body.message).toEqual(['code must be a string', 'name must be a string']);
        });
    });

    test('ignores extraneous parameters in body', async () => {
      await request(app.getHttpServer())
        .post('/program')
        .send({name: 'name', code: 'code', extraneous: 'property'})
        .expect(201);

      expect(neo4jService.execute.mock.calls[0][1]).not.toHaveProperty('extraneous');
    });

    test('executes correct query with parameters', async () => {
      // act
      await programController.createProgram({fake: 'property'});
      
      // asserts
      
      // exactly 1 call to execute
      expect(neo4jService.execute).toBeCalledTimes(1);
      // first parameter is correct query
      expect(neo4jService.execute.mock.calls[0][0]).toEqual(Queries.createProgram);
      
      const props = neo4jService.execute.mock.calls[0][1]
      // second parameter has props
      expect(props).toHaveProperty('props');
      // fake property is propagated
      expect(props.props).toHaveProperty('fake', 'property')
      // uuid is generated by controller
      expect(props.props).toHaveProperty('uuid')
      expect(validUuidV4(props.props.uuid)).toBe(true);
    });
  });

  describe('updating program node', () => {
    test('rejects an invalid uuid', async () => {
      await request(app.getHttpServer())
        .put('/program/not-a-uuid')
        .send({name: 'name', code: 'code'})
        .expect(400)
        .then(response => {
          expect(response.body.message).toBe('Validation failed (uuid v4 is expected)');
        })
    });
    
    test('rejects with empty name and code', async () => {
      await request(app.getHttpServer())
        .put(`/program/${generateUuid()}`)
        .send({name: '', code: ''})
        .expect(400)
        .then(response => {
          expect(response.body.message).toEqual(['code should not be empty', 'name should not be empty']);
        });
    });
  
    test('rejects with name and code not a string', async () => {
      await request(app.getHttpServer())
        .put(`/program/${generateUuid()}`)
        .send({name: 5, code: 5})
        .expect(400)
        .then(response => {
          expect(response.body.message).toEqual(['code must be a string', 'name must be a string']);
        });
    });
  
    test('ignores extraneous parameters in body', async () => {
      await request(app.getHttpServer())
        .put(`/program/${generateUuid()}`)
        .send({name: 'name', code: 'code', extraneous: 'property'})
        .expect(200);
  
      expect(neo4jService.execute.mock.calls[0][1]).toHaveProperty('props');
      expect(neo4jService.execute.mock.calls[0][1].props).not.toHaveProperty('extraneous');
    });
      
    test('executes correct query with parameters', async () => {
      // arrange
      const uuid = generateUuid();
  
      // act
      await programController.updateProgram(uuid, {fake: 'property'});
  
      // asserts
  
      // exactly 1 call to execute
      expect(neo4jService.execute).toBeCalledTimes(1);
      // first parameter is correct query
      expect(neo4jService.execute.mock.calls[0][0]).toEqual(Queries.updateProgram);
  
      const props = neo4jService.execute.mock.calls[0][1]
      // second parameter has props
      expect(props).toHaveProperty('props');
      // fake property is propagated
      expect(props.props).toHaveProperty('fake', 'property')
      // check that correct uuid is passed
      expect(props).toHaveProperty('uuid')
      expect(props.uuid).toBe(uuid);
    });
  });

  describe('deleting program node', () => {
    test('rejects an invalid uuid', async () => {
      await request(app.getHttpServer())
        .delete('/program/not-a-uuid')
        .expect(400)
        .then(response => {
          expect(response.body.message).toBe('Validation failed (uuid v4 is expected)');
        })
    });
  
    test('executes correct query with parameters', async () => {
      // arrange
      const uuid = generateUuid();
  
      // act
      await programController.deleteProgram(uuid);
  
      // asserts
  
      // exactly 1 call to execute
      expect(neo4jService.execute).toBeCalledTimes(1);
      // first parameter is correct query
      expect(neo4jService.execute.mock.calls[0][0]).toEqual(Queries.deleteNode);
  
      const props = neo4jService.execute.mock.calls[0][1]
      // check that correct uuid is passed
      expect(props).toHaveProperty('uuid')
      expect(props.uuid).toBe(uuid);
    });
  });
})
